{% set version = "0.0.6" %}

package:
  name: geocube
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geocube/geocube-{{ version }}.tar.gz
  sha256: d202a927cef5b7e5baa363b8131dc8c77ed6959f3536a5bcc51658068967b332

build:
  number: 0
  noarch: python
  entry_points:
    - geocube=geocube.cli.geocube:geocube
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - appdirs
    - click >=6.0
    - datacube >=1.6.2,<1.7
    - geopandas
    - python
    - rasterio
    - rioxarray
    - xarray

test:
  imports:
    - geocube
    - geocube.api
    - geocube.geo_utils
    - geocube.xarray_extensions
  commands:
    - geocube --help
  requires:
    - mock
    - pytest >=3.6
    - pytest-cov

about:
  home: https://github.com/corteva/geocube
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tool to convert geopandas vector data into rasterized xarray data

extra:
  recipe-maintainers:
    - snowman2
    - ocefpaf
