{% set version = "0.0.8" %}

package:
  name: geocube
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geocube/geocube-{{ version }}.tar.gz
  sha256: 62bc6d4d2c7404d094282bdd0f815692b035e844e74dcc0699fa5629b4eb084c

build:
  number: 0
  noarch: python
  entry_points:
    - geocube=geocube.cli.geocube:geocube
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python 3
    - pip
  run:
    - appdirs
    - click >=6.0
    - datacube
    - geopandas
    - python 3
    - rasterio
    - rioxarray
    - xarray

test:
  imports:
    - geocube
    - geocube.api
    - geocube.geo_utils
    - geocube.xarray_extensions
  commands:
    - geocube --help
  requires:
    - mock
    - pytest >=3.6
    - pytest-cov

about:
  home: https://github.com/corteva/geocube
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tool to convert geopandas vector data into rasterized xarray data

extra:
  recipe-maintainers:
    - snowman2
    - ocefpaf
