travis:
  secure:
    BINSTAR_TOKEN: BJjNMcIgqLwRuACfTuD6kIvRc1EIBYO1o6diNN0LWbf/gYHuNm20qx9O8IXgBWjb5qYR+MsHNAikCOLegiAoV4jaadoDLTKvCpgegJB/GY556eqf+o/vAn5Ak14UzU1fDFMg2f4eaeci9BTtHM93qEA2ZUT5mO4v9Ju+5L9KGtl4VQMBRII9MxwjLQctyJlVV3ouBQbvSB1WdwIQ2WBgc0szZXdWZJ4bHwQXXiuwRkjYQKC+4v7Wogk3e6ny9f+hxd0c6mbueRspRll+yXmD1Eg82To2lG4sdXBVh1b2cvnTakf3IwPcefxPbZuH29bs4o9dstn63+nrQ6s/BGN5gdGmHEuXbE2KCFVwj+qTxC/+MlTcaUq7Qgr1Sr4a/k5JQDcNicqEvjRP8rtOvcKuLTtqgBw8j7oBzbFO5CTQ1gMn3nYUlnZwPFlYuDLlxCviGZbek5Ve/0W/sKYuHgurKKo+zMJQdfIXNhySwU2OT+yi10iBk17TNeVoEz3vuKFstFrOvmrroCKeVXen1XVghpBAq4BHdhnapthFhgd35Bfuc2PNxhx6ur08yMVaKVYYMeqWLuFgskS0kFvNNg+fVHsIgFfcEvsl2fy98jD2TrLnlX51HHEBAIyoMPmhJWv7tSX0k5AbIdxZWCj/IGIr1I/mlScLdR9WF2WpkbrDHrM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
